### ISSUE TITLE
Server crashes if network connection is unstable on startup

### ISSUE THREAD

**Issue by derwaldgeist** [carlodicelico/tokbox-meteor#11]
I'm prototyping my app while sitting in a train with an unstable network connection. Here, I've noticed that the server crashes if the network connection to the OpenTok servers is not available on startup.

Here's the error message:
```js
TypeError: Cannot read property 'sessionId' of undefined 
   at packages/carlodicelico:tokbox/server/index.js:13:1
```

Seems as if an undefined check is missing at this code line.

Of course it is not a productive scenario to test the server over an unstable connection. But if this also happens if the OpenTok server is not available due to a downtime, this would also be a problem in a productive scenario.

**Comment by floydnoel** [comment]
I'm getting a similar error but unsure what the cause is.

```
TypeError: Cannot read property 'sessionId' of undefined
    at packages/carlodicelico_tokbox/packages/carlodicelico_tokbox.js:21:1
```
