### ISSUE TITLE
Abandoned package?

### ISSUE THREAD

**Issue by dandv** [carlodicelico/tokbox-meteor#12]
1. https://github.com/aspin/tokbox-meteor says this package is broken. Are there any updates planned? If not, it would be great to [remove it from Atmosphere](https://github.com/percolatestudio/atmosphere/issues/267#issuecomment-58769824).

2. Is this package necessary now that [Meteor 1.3 can use NPM modules directly](https://guide.meteor.com/1.3-migration.html#modules)?

**Comment by carlodicelico** [comment]
I'd like to keep it up just for people who are still pre-1.3. I've tested and it seems to be working but it is open source - if something specific is going on, people are welcome to contribute!
		_____________________________

**Comment by carlodicelico** [comment]
Yeah, to see this version being used in production, visit Vonvo.com, create an account and join a chat room. So it's still working properly. 



On Wed, Jul 27, 2016 at 7:31 AM -0400, <carlodicelico@me.com> wrote:











		I'd like to keep it up just for people who are still pre-1.3. I've tested and it seems to be working but it is open source - if something specific is going on, people are welcome to contribute!
		_____________________________
