### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by johngonzalez** [carlodicelico/tokbox-meteor#8]
Exits a problem in android device, is not possible create a session in client:
var session = OT.initSession(apiKey, sessionId);
I get this exit:
XMLHttpRequest cannot load http://.../sockjs/362/905_lm05/xhr. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.

**Comment by hemant4bluepi** [comment]
Facing a same problem....
OT.checkSystemRequirements() returns false..............did u find any help

**Comment by carlodicelico** [comment]
You would need to check in the Tokbox API for mobile WebRTC support.
